services:
  tasktracker.webapi:
    image: tasktracker.webapi
    build:
      context: .
      dockerfile: TaskTracker.WebAPI/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - tasktracker.db
  
  tasktracker.client:
    image: tasktracker.client
    build:
     context: ./tasktracker-app
     dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./tasktracker-app:/app
      - /app/node_modules
    stdin_open: true
    depends_on:
      - tasktracker.webapi
       
  tasktracker.db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: deva
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tasktracker
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U deva -d tasktracker" ]
      interval: 30s
      timeout: 10s
      retries: 3
    
volumes:
  pgdata: